package com.jn.db.dao;

import com.jn.db.domain.JnAdmin;
import com.jn.db.domain.JnAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     */
    long countByExample(JnAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     */
    int deleteByExample(JnAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     */
    int insert(JnAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     */
    int insertSelective(JnAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnAdmin selectOneByExample(JnAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnAdmin selectOneByExampleSelective(@Param("example") JnAdminExample example, @Param("selective") JnAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnAdmin> selectByExampleSelective(@Param("example") JnAdminExample example, @Param("selective") JnAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     */
    List<JnAdmin> selectByExample(JnAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     */
    JnAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnAdmin record, @Param("example") JnAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnAdmin record, @Param("example") JnAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") JnAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}