package com.jn.db.dao;

import com.jn.db.domain.JnArticle;
import com.jn.db.domain.JnArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     */
    long countByExample(JnArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     */
    int deleteByExample(JnArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     */
    int insert(JnArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     */
    int insertSelective(JnArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnArticle selectOneByExample(JnArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnArticle selectOneByExampleSelective(@Param("example") JnArticleExample example, @Param("selective") JnArticle.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnArticle selectOneByExampleWithBLOBs(JnArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnArticle> selectByExampleSelective(@Param("example") JnArticleExample example, @Param("selective") JnArticle.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     */
    List<JnArticle> selectByExampleWithBLOBs(JnArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     */
    List<JnArticle> selectByExample(JnArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnArticle selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnArticle.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     */
    JnArticle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnArticle selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnArticle record, @Param("example") JnArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") JnArticle record, @Param("example") JnArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnArticle record, @Param("example") JnArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(JnArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") JnArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}