package com.jn.db.dao;

import com.jn.db.domain.JnBooksProduct;
import com.jn.db.domain.JnBooksProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnBooksProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     */
    long countByExample(JnBooksProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     */
    int deleteByExample(JnBooksProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     */
    int insert(JnBooksProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     */
    int insertSelective(JnBooksProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooksProduct selectOneByExample(JnBooksProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooksProduct selectOneByExampleSelective(@Param("example") JnBooksProductExample example, @Param("selective") JnBooksProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnBooksProduct> selectByExampleSelective(@Param("example") JnBooksProductExample example, @Param("selective") JnBooksProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     */
    List<JnBooksProduct> selectByExample(JnBooksProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooksProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnBooksProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     */
    JnBooksProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooksProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnBooksProduct record, @Param("example") JnBooksProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnBooksProduct record, @Param("example") JnBooksProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnBooksProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnBooksProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") JnBooksProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}