package com.jn.db.dao;

import com.jn.db.domain.JnBooks;
import com.jn.db.domain.JnBooksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnBooksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     */
    long countByExample(JnBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     */
    int deleteByExample(JnBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     */
    int insert(JnBooks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     */
    int insertSelective(JnBooks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooks selectOneByExample(JnBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooks selectOneByExampleSelective(@Param("example") JnBooksExample example, @Param("selective") JnBooks.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooks selectOneByExampleWithBLOBs(JnBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnBooks> selectByExampleSelective(@Param("example") JnBooksExample example, @Param("selective") JnBooks.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     */
    List<JnBooks> selectByExampleWithBLOBs(JnBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     */
    List<JnBooks> selectByExample(JnBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooks selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnBooks.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     */
    JnBooks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooks selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnBooks record, @Param("example") JnBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") JnBooks record, @Param("example") JnBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnBooks record, @Param("example") JnBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnBooks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(JnBooks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnBooks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") JnBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}