package com.jn.db.dao;

import com.jn.db.domain.JnBooksSpecification;
import com.jn.db.domain.JnBooksSpecificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnBooksSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     */
    long countByExample(JnBooksSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     */
    int deleteByExample(JnBooksSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     */
    int insert(JnBooksSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     */
    int insertSelective(JnBooksSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooksSpecification selectOneByExample(JnBooksSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooksSpecification selectOneByExampleSelective(@Param("example") JnBooksSpecificationExample example, @Param("selective") JnBooksSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnBooksSpecification> selectByExampleSelective(@Param("example") JnBooksSpecificationExample example, @Param("selective") JnBooksSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     */
    List<JnBooksSpecification> selectByExample(JnBooksSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooksSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnBooksSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     */
    JnBooksSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooksSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnBooksSpecification record, @Param("example") JnBooksSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnBooksSpecification record, @Param("example") JnBooksSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnBooksSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnBooksSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") JnBooksSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}