package com.jn.db.dao;

import com.jn.db.domain.JnBooksAttribute;
import com.jn.db.domain.JnBooksAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnBooksAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     */
    long countByExample(JnBooksAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(JnBooksAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     */
    int insert(JnBooksAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     */
    int insertSelective(JnBooksAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooksAttribute selectOneByExample(JnBooksAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooksAttribute selectOneByExampleSelective(@Param("example") JnBooksAttributeExample example, @Param("selective") JnBooksAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnBooksAttribute> selectByExampleSelective(@Param("example") JnBooksAttributeExample example, @Param("selective") JnBooksAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     */
    List<JnBooksAttribute> selectByExample(JnBooksAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooksAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnBooksAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     */
    JnBooksAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnBooksAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnBooksAttribute record, @Param("example") JnBooksAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnBooksAttribute record, @Param("example") JnBooksAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnBooksAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnBooksAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") JnBooksAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_books_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}