package com.jn.db.dao;

import com.jn.db.domain.JnCategory;
import com.jn.db.domain.JnCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     */
    long countByExample(JnCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     */
    int deleteByExample(JnCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     */
    int insert(JnCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     */
    int insertSelective(JnCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnCategory selectOneByExample(JnCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnCategory selectOneByExampleSelective(@Param("example") JnCategoryExample example, @Param("selective") JnCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnCategory> selectByExampleSelective(@Param("example") JnCategoryExample example, @Param("selective") JnCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     */
    List<JnCategory> selectByExample(JnCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     */
    JnCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnCategory record, @Param("example") JnCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnCategory record, @Param("example") JnCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") JnCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}