package com.jn.db.dao;

import com.jn.db.domain.JnComment;
import com.jn.db.domain.JnCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     */
    long countByExample(JnCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     */
    int deleteByExample(JnCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     */
    int insert(JnComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     */
    int insertSelective(JnComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnComment selectOneByExample(JnCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnComment selectOneByExampleSelective(@Param("example") JnCommentExample example, @Param("selective") JnComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnComment> selectByExampleSelective(@Param("example") JnCommentExample example, @Param("selective") JnComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     */
    List<JnComment> selectByExample(JnCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     */
    JnComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnComment record, @Param("example") JnCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnComment record, @Param("example") JnCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") JnCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}