package com.jn.db.dao;

import com.jn.db.domain.JnFeedback;
import com.jn.db.domain.JnFeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     */
    long countByExample(JnFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     */
    int deleteByExample(JnFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     */
    int insert(JnFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     */
    int insertSelective(JnFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnFeedback selectOneByExample(JnFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnFeedback selectOneByExampleSelective(@Param("example") JnFeedbackExample example, @Param("selective") JnFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnFeedback> selectByExampleSelective(@Param("example") JnFeedbackExample example, @Param("selective") JnFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     */
    List<JnFeedback> selectByExample(JnFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnFeedback selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     */
    JnFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnFeedback selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnFeedback record, @Param("example") JnFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnFeedback record, @Param("example") JnFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") JnFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}