package com.jn.db.dao;

import com.jn.db.domain.JnFootprint;
import com.jn.db.domain.JnFootprintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    long countByExample(JnFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int deleteByExample(JnFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int insert(JnFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int insertSelective(JnFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnFootprint selectOneByExample(JnFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnFootprint selectOneByExampleSelective(@Param("example") JnFootprintExample example, @Param("selective") JnFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnFootprint> selectByExampleSelective(@Param("example") JnFootprintExample example, @Param("selective") JnFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    List<JnFootprint> selectByExample(JnFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    JnFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnFootprint record, @Param("example") JnFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnFootprint record, @Param("example") JnFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") JnFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}
