package com.jn.db.dao;

import com.jn.db.domain.JnOrder;
import com.jn.db.domain.JnOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     */
    long countByExample(JnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     */
    int deleteByExample(JnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     */
    int insert(JnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     */
    int insertSelective(JnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnOrder selectOneByExample(JnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnOrder selectOneByExampleSelective(@Param("example") JnOrderExample example, @Param("selective") JnOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnOrder> selectByExampleSelective(@Param("example") JnOrderExample example, @Param("selective") JnOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     */
    List<JnOrder> selectByExample(JnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     */
    JnOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnOrder record, @Param("example") JnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnOrder record, @Param("example") JnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") JnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}