package com.jn.db.dao;

import com.jn.db.domain.JnOrderBooks;
import com.jn.db.domain.JnOrderBooksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnOrderBooksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     */
    long countByExample(JnOrderBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     */
    int deleteByExample(JnOrderBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     */
    int insert(JnOrderBooks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     */
    int insertSelective(JnOrderBooks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnOrderBooks selectOneByExample(JnOrderBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnOrderBooks selectOneByExampleSelective(@Param("example") JnOrderBooksExample example, @Param("selective") JnOrderBooks.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnOrderBooks> selectByExampleSelective(@Param("example") JnOrderBooksExample example, @Param("selective") JnOrderBooks.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     */
    List<JnOrderBooks> selectByExample(JnOrderBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnOrderBooks selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnOrderBooks.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     */
    JnOrderBooks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnOrderBooks selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnOrderBooks record, @Param("example") JnOrderBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnOrderBooks record, @Param("example") JnOrderBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnOrderBooks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnOrderBooks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") JnOrderBooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_order_books
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}