package com.jn.db.dao;

import com.jn.db.domain.JnRegion;
import com.jn.db.domain.JnRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_region
     *
     * @mbg.generated
     */
    long countByExample(JnRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_region
     *
     * @mbg.generated
     */
    int deleteByExample(JnRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_region
     *
     * @mbg.generated
     */
    int insert(JnRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_region
     *
     * @mbg.generated
     */
    int insertSelective(JnRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnRegion selectOneByExample(JnRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnRegion selectOneByExampleSelective(@Param("example") JnRegionExample example, @Param("selective") JnRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnRegion> selectByExampleSelective(@Param("example") JnRegionExample example, @Param("selective") JnRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_region
     *
     * @mbg.generated
     */
    List<JnRegion> selectByExample(JnRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_region
     *
     * @mbg.generated
     */
    JnRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnRegion record, @Param("example") JnRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnRegion record, @Param("example") JnRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnRegion record);
}