package com.jn.db.dao;

import com.jn.db.domain.JnStorage;
import com.jn.db.domain.JnStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     */
    long countByExample(JnStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     */
    int deleteByExample(JnStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     */
    int insert(JnStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     */
    int insertSelective(JnStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnStorage selectOneByExample(JnStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnStorage selectOneByExampleSelective(@Param("example") JnStorageExample example, @Param("selective") JnStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnStorage> selectByExampleSelective(@Param("example") JnStorageExample example, @Param("selective") JnStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     */
    List<JnStorage> selectByExample(JnStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     */
    JnStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnStorage record, @Param("example") JnStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnStorage record, @Param("example") JnStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") JnStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}