package com.jn.db.dao;

import com.jn.db.domain.JnSystem;
import com.jn.db.domain.JnSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     */
    long countByExample(JnSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     */
    int deleteByExample(JnSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     */
    int insert(JnSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     */
    int insertSelective(JnSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnSystem selectOneByExample(JnSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnSystem selectOneByExampleSelective(@Param("example") JnSystemExample example, @Param("selective") JnSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnSystem> selectByExampleSelective(@Param("example") JnSystemExample example, @Param("selective") JnSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     */
    List<JnSystem> selectByExample(JnSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     */
    JnSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnSystem record, @Param("example") JnSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnSystem record, @Param("example") JnSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") JnSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}