package com.jn.db.dao;

import com.jn.db.domain.JnTopic;
import com.jn.db.domain.JnTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     */
    long countByExample(JnTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     */
    int deleteByExample(JnTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     */
    int insert(JnTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     */
    int insertSelective(JnTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnTopic selectOneByExample(JnTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnTopic selectOneByExampleSelective(@Param("example") JnTopicExample example, @Param("selective") JnTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnTopic selectOneByExampleWithBLOBs(JnTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnTopic> selectByExampleSelective(@Param("example") JnTopicExample example, @Param("selective") JnTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     */
    List<JnTopic> selectByExampleWithBLOBs(JnTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     */
    List<JnTopic> selectByExample(JnTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     */
    JnTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnTopic record, @Param("example") JnTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") JnTopic record, @Param("example") JnTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnTopic record, @Param("example") JnTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(JnTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") JnTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}