package com.jn.db.dao;

import com.jn.db.domain.JnUserAccount;
import com.jn.db.domain.JnUserAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JnUserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_user_account
     *
     * @mbg.generated
     */
    long countByExample(JnUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_user_account
     *
     * @mbg.generated
     */
    int deleteByExample(JnUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_user_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_user_account
     *
     * @mbg.generated
     */
    int insert(JnUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_user_account
     *
     * @mbg.generated
     */
    int insertSelective(JnUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_user_account
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnUserAccount selectOneByExample(JnUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_user_account
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnUserAccount selectOneByExampleSelective(@Param("example") JnUserAccountExample example, @Param("selective") JnUserAccount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_user_account
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<JnUserAccount> selectByExampleSelective(@Param("example") JnUserAccountExample example, @Param("selective") JnUserAccount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_user_account
     *
     * @mbg.generated
     */
    List<JnUserAccount> selectByExample(JnUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_user_account
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JnUserAccount selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JnUserAccount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_user_account
     *
     * @mbg.generated
     */
    JnUserAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_user_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JnUserAccount record, @Param("example") JnUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_user_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JnUserAccount record, @Param("example") JnUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_user_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JnUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jn_user_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JnUserAccount record);
}